# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ShortLinkGenerator.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_ShortLinkGenerator(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(736, 433)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background: #272822;\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(15, 60, 706, 361))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"    border: 2px solid #eeeeee;\n"
"    top:-1px; \n"
"  \n"
"\n"
"} \n"
"\n"
"QTabBar::tab {\n"
"  color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#ffffff, stop:1 #abbaab);\n"
"  \n"
"  padding: 10px;\n"
"  background-color: #272822;\n"
"}\n"
"\n"
"QTabBar::tab:selected { \n"
"  border-bottom: 2px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,stop:0 #5488ff,stop:1 #a5fecb);\n"
"  border-left: 2px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,stop:0 #5488ff,stop:1 #a5fecb);\n"
"  border-right: 2px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,stop:0 #5488ff,stop:1 #a5fecb);\n"
"  border-right: 2px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,stop:0 #5488ff,stop:1 #a5fecb);\n"
"\n"
"  color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,stop:0 #5488ff,stop:1 #a5fecb);\n"
"  margin-bottom: -1px; \n"
"}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Generator = QtWidgets.QWidget()
        self.Generator.setObjectName("Generator")
        self.generateshortlink = QtWidgets.QPushButton(self.Generator)
        self.generateshortlink.setGeometry(QtCore.QRect(15, 75, 181, 46))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generateshortlink.sizePolicy().hasHeightForWidth())
        self.generateshortlink.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.generateshortlink.setFont(font)
        self.generateshortlink.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.generateshortlink.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#ffff00, stop:1 #ffa733);\n"
"color : rgba(0, 0,0);\n"
"border-radius:4px;\n"
"\n"
"")
        self.generateshortlink.setObjectName("generateshortlink")
        self.shortlinktxt = QtWidgets.QLineEdit(self.Generator)
        self.shortlinktxt.setGeometry(QtCore.QRect(210, 240, 481, 46))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.shortlinktxt.setFont(font)
        self.shortlinktxt.setStyleSheet("color : #ffd31a;\n"
"padding-left: 10;\n"
"border: 2px solid #eeeeee;")
        self.shortlinktxt.setText("")
        self.shortlinktxt.setFrame(True)
        self.shortlinktxt.setAlignment(QtCore.Qt.AlignCenter)
        self.shortlinktxt.setDragEnabled(False)
        self.shortlinktxt.setReadOnly(False)
        self.shortlinktxt.setClearButtonEnabled(True)
        self.shortlinktxt.setObjectName("shortlinktxt")
        self.customurl = QtWidgets.QLineEdit(self.Generator)
        self.customurl.setGeometry(QtCore.QRect(345, 157, 346, 46))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.customurl.setFont(font)
        self.customurl.setStyleSheet("color : #ffd31a;\n"
"padding-left: 10;\n"
"border: 2px solid #eeeeee;")
        self.customurl.setText("")
        self.customurl.setFrame(True)
        self.customurl.setDragEnabled(False)
        self.customurl.setReadOnly(False)
        self.customurl.setClearButtonEnabled(True)
        self.customurl.setObjectName("customurl")
        self.Pastelongurl = QtWidgets.QPushButton(self.Generator)
        self.Pastelongurl.setGeometry(QtCore.QRect(15, 15, 181, 46))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Pastelongurl.sizePolicy().hasHeightForWidth())
        self.Pastelongurl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.Pastelongurl.setFont(font)
        self.Pastelongurl.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Pastelongurl.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#ffff00, stop:1 #ffa733);\n"
"color : rgba(0, 0,0);\n"
"border-radius:4px;\n"
"\n"
"")
        self.Pastelongurl.setObjectName("Pastelongurl")
        self.longurl = QtWidgets.QPlainTextEdit(self.Generator)
        self.longurl.setGeometry(QtCore.QRect(210, 15, 481, 106))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.longurl.setFont(font)
        self.longurl.setStyleSheet("color : #ffd31a;\n"
"padding-left: 10;\n"
"border: 2px solid #eeeeee;")
        self.longurl.setObjectName("longurl")
        self.titleurl = QtWidgets.QLineEdit(self.Generator)
        self.titleurl.setGeometry(QtCore.QRect(15, 157, 316, 46))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.titleurl.setFont(font)
        self.titleurl.setStyleSheet("color : #ffd31a;\n"
"padding-left: 10;\n"
"border: 2px solid #eeeeee;")
        self.titleurl.setText("")
        self.titleurl.setFrame(True)
        self.titleurl.setDragEnabled(False)
        self.titleurl.setReadOnly(False)
        self.titleurl.setClearButtonEnabled(True)
        self.titleurl.setObjectName("titleurl")
        self.copyshorturl = QtWidgets.QPushButton(self.Generator)
        self.copyshorturl.setGeometry(QtCore.QRect(15, 240, 181, 46))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copyshorturl.sizePolicy().hasHeightForWidth())
        self.copyshorturl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.copyshorturl.setFont(font)
        self.copyshorturl.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.copyshorturl.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#ffff00, stop:1 #ffa733);\n"
"color : rgba(0, 0,0);\n"
"border-radius:4px;\n"
"\n"
"")
        self.copyshorturl.setObjectName("copyshorturl")
        self.generateshortlink.raise_()
        self.shortlinktxt.raise_()
        self.Pastelongurl.raise_()
        self.longurl.raise_()
        self.copyshorturl.raise_()
        self.customurl.raise_()
        self.titleurl.raise_()
        self.tabWidget.addTab(self.Generator, "")
        self.Links = QtWidgets.QWidget()
        self.Links.setObjectName("Links")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.Links)
        self.plainTextEdit.setEnabled(True)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 70, 706, 241))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.plainTextEdit.setStyleSheet("color : #d5ddd5;\n"
"border-top: 2px solid #eeeeee;")
        self.plainTextEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.plainTextEdit.setReadOnly(False)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setOverwriteMode(False)
        self.plainTextEdit.setTextInteractionFlags(QtCore.Qt.TextEditorInteraction)
        self.plainTextEdit.setPlaceholderText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.dellink = QtWidgets.QPushButton(self.Links)
        self.dellink.setGeometry(QtCore.QRect(130, 12, 91, 46))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dellink.sizePolicy().hasHeightForWidth())
        self.dellink.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.dellink.setFont(font)
        self.dellink.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dellink.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#fdfc47, stop:1 #24fe41);\n"
"color : rgba(0, 0,0);\n"
"border-radius:4px;\n"
"\n"
"")
        self.dellink.setObjectName("dellink")
        self.deltxt = QtWidgets.QLineEdit(self.Links)
        self.deltxt.setGeometry(QtCore.QRect(230, 12, 461, 46))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.deltxt.setFont(font)
        self.deltxt.setStyleSheet("color : #91fd44;\n"
"padding-left: 10;\n"
"border: 2px solid #eeeeee;")
        self.deltxt.setText("")
        self.deltxt.setFrame(True)
        self.deltxt.setDragEnabled(False)
        self.deltxt.setReadOnly(False)
        self.deltxt.setClearButtonEnabled(True)
        self.deltxt.setObjectName("deltxt")
        self.loadlinks = QtWidgets.QPushButton(self.Links)
        self.loadlinks.setGeometry(QtCore.QRect(10, 12, 111, 46))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadlinks.sizePolicy().hasHeightForWidth())
        self.loadlinks.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.loadlinks.setFont(font)
        self.loadlinks.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loadlinks.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#fdfc47, stop:1 #24fe41);\n"
"color : rgba(0, 0,0);\n"
"border-radius:4px;\n"
"\n"
"")
        self.loadlinks.setObjectName("loadlinks")
        self.tabWidget.addTab(self.Links, "")
        self.BackgroundBehind_2 = QtWidgets.QLabel(self.centralwidget)
        self.BackgroundBehind_2.setEnabled(True)
        self.BackgroundBehind_2.setGeometry(QtCore.QRect(15, 15, 706, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BackgroundBehind_2.sizePolicy().hasHeightForWidth())
        self.BackgroundBehind_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.BackgroundBehind_2.setFont(font)
        self.BackgroundBehind_2.setToolTipDuration(0)
        self.BackgroundBehind_2.setAutoFillBackground(False)
        self.BackgroundBehind_2.setStyleSheet("background: #272822;\n"
"border-radius:5px;\n"
"")
        self.BackgroundBehind_2.setInputMethodHints(QtCore.Qt.ImhNoPredictiveText)
        self.BackgroundBehind_2.setText("")
        self.BackgroundBehind_2.setAlignment(QtCore.Qt.AlignCenter)
        self.BackgroundBehind_2.setObjectName("BackgroundBehind_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(15, 377, 185, 2))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,stop:0 #5488ff,stop:1 #a5fecb);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(600, 10, 121, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.help_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.help_btn.setMinimumSize(QtCore.QSize(18, 18))
        self.help_btn.setMaximumSize(QtCore.QSize(18, 18))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setBold(True)
        font.setWeight(75)
        self.help_btn.setFont(font)
        self.help_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.help_btn.setStyleSheet("background-color: rgb(5,195,221);\n"
"color: rgb(0, 0, 0);\n"
"border-radius:8px;")
        self.help_btn.setObjectName("help_btn")
        self.horizontalLayout.addWidget(self.help_btn)
        self.pushButtonMinimize = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonMinimize.setMinimumSize(QtCore.QSize(18, 18))
        self.pushButtonMinimize.setMaximumSize(QtCore.QSize(18, 18))
        self.pushButtonMinimize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonMinimize.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"border-radius:8px;")
        self.pushButtonMinimize.setText("")
        self.pushButtonMinimize.setObjectName("pushButtonMinimize")
        self.horizontalLayout.addWidget(self.pushButtonMinimize)
        self.pushButtonMaximiz = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonMaximiz.setMinimumSize(QtCore.QSize(18, 18))
        self.pushButtonMaximiz.setMaximumSize(QtCore.QSize(18, 18))
        self.pushButtonMaximiz.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonMaximiz.setStyleSheet("background-color: rgb(255, 226, 0);\n"
"border-radius:8px;")
        self.pushButtonMaximiz.setText("")
        self.pushButtonMaximiz.setObjectName("pushButtonMaximiz")
        self.horizontalLayout.addWidget(self.pushButtonMaximiz)
        self.pushButtonExit = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonExit.setMinimumSize(QtCore.QSize(18, 18))
        self.pushButtonExit.setMaximumSize(QtCore.QSize(18, 18))
        self.pushButtonExit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonExit.setStyleSheet("background-color:rgb(255, 97, 6);\n"
"border-radius:8px;")
        self.pushButtonExit.setText("")
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.horizontalLayout.addWidget(self.pushButtonExit)
        self.BackgroundBehind_2.raise_()
        self.tabWidget.raise_()
        self.label.raise_()
        self.layoutWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.pushButtonExit.clicked.connect(MainWindow.close) # type: ignore
        self.pushButtonMinimize.clicked.connect(MainWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.generateshortlink.setText(_translate("MainWindow", "GENERATE LINK"))
        self.shortlinktxt.setPlaceholderText(_translate("MainWindow", "Your Short-Link"))
        self.customurl.setPlaceholderText(_translate("MainWindow", "Custom URL (optional)"))
        self.Pastelongurl.setText(_translate("MainWindow", "PASTE LONG URL"))
        self.longurl.setPlaceholderText(_translate("MainWindow", "Enter The Long URL "))
        self.titleurl.setPlaceholderText(_translate("MainWindow", "Title URL (optional)"))
        self.copyshorturl.setText(_translate("MainWindow", "Copy URL"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Generator), _translate("MainWindow", "Generator"))
        self.dellink.setText(_translate("MainWindow", "DELETE"))
        self.deltxt.setPlaceholderText(_translate("MainWindow", "Enter The Link-ID You Want To Delete"))
        self.loadlinks.setText(_translate("MainWindow", "LOAD URLS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Links), _translate("MainWindow", "Links"))
        self.help_btn.setText(_translate("MainWindow", "H"))